apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace configuration - change this to deploy to a different namespace
namespace: rhaiis

# Resources to deploy
resources:

  # Inference server Deployment
  - namespace-rolebinding.yaml.local
  - pvc.yaml.local
  - deployment.yaml.local
  - service.yaml.local
  - route.yaml.local
